# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jay Patel's Personal Website
email: jaypatel.bdq@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  Explore expert insights and projects on Python, Machine Learning, Deep Learning, Data Science, Data Engineering, and Full Stack Development. 
  Dive into tutorials, best practices, and innovative techniques that will help you master these fields. 
  Stay updated with the latest trends and enhance your skills through detailed guides and hands-on examples.
github_username: bdqjay
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Helsinki

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jay Patel"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Passionate about Data Science, Machine Learning, Data Engineering, and Full-Stack."
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin"
      url: "https://fi.linkedin.com/in/jay-n-patel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bdqjay"

footer:
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin"
      url: "https://fi.linkedin.com/in/jay-n-patel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bdqjay"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
